name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install

      - name: Run Tests (optional)
        run: |
          cd backend
          npm test
          cd ../frontend
          npm test

      - name: Build and Deploy
        run: |
          cd frontend
          npm run build
          vercel --prod
